//
//  DummyHeroes.swift
//  MyHero
//
//  Created by SLYTH on 08/04/21.
//

import UIKit
let heroes = [
  Hero(id: 1, photo: "ahmad_dahlan", name: "Ahmad Dahlan", description: "Kiai Haji Ahmad Dahlan atau Muhammad Darwis (bahasa Arab: أحمد دحلان‎; lahir di Yogyakarta, 1 Agustus 1868 – meninggal di Yogyakarta, 23 Februari 1923 pada umur 54 tahun) adalah seorang Pahlawan Nasional Indonesia yang merupakan pendiri Muhammadiyah. Dia adalah putra keempat dari tujuh bersaudara dari keluarga K.H. Abu Bakar. KH Abu Bakar adalah seorang ulama dan khatib terkemuka di Masjid Besar Kasultanan Yogyakarta pada masa itu, dan ibu dari K.H. Ahmad Dahlan adalah puteri dari H. Ibrahim yang juga menjabat penghulu Kesultanan Ngayogyakarta Hadiningrat pada masa itu"),
  Hero(id: 2, photo: "ahmad_yani", name: "Ahmad Yani", description: "Ahmad Yani lahir di Jenar, Purworejo, Jawa Tengah pada tanggal 19 Juni 1922 di keluarga Wongsoredjo, keluarga yang bekerja di sebuah pabrik gula yang dijalankan oleh pemilik Belanda. Pada tahun 1927, Yani pindah dengan keluarganya ke Batavia, di mana ayahnya kini bekerja untuk General Belanda. Di Batavia, Yani bekerja jalan melalui pendidikan dasar dan menengah. Pada tahun 1940, Yani meninggalkan sekolah tinggi untuk menjalani wajib militer di tentara Hindia Belanda pemerintah kolonial. Ia belajar topografi militer di Malang, Jawa Timur, tetapi pendidikan ini terganggu oleh kedatangan pasukan Jepang pada tahun 1942. Pada saat yang sama, Yani dan keluarganya pindah kembali ke Jawa Tengah."),
  Hero(id: 3, photo: "bung_tomo", name: "Bung Tomo", description: "Sutomo (lahir di Surabaya, Jawa Timur, 3 Oktober 1920 – meninggal di Padang Arafah, Arab Saudi, 7 Oktober 1981 pada umur 61 tahun)[1] lebih dikenal dengan sapaan akrab oleh rakyat sebagai Bung Tomo, adalah pahlawan yang terkenal karena peranannya dalam membangkitkan semangat rakyat untuk melawan kembalinya penjajah Belanda melalui tentara NICA, yang berakhir dengan pertempuran 10 November 1945 yang hingga kini diperingati sebagai Hari Pahlawan"),
  Hero(id: 4, photo: "supomo", name: "Soepomo", description:"Prof. Dr. Mr. Soepomo (Ejaan Soewandi: Supomo; lahir di Sukoharjo, Jawa Tengah, 22 Januari 1903 – meninggal di Jakarta, 12 September 1958 pada umur 55 tahun) adalah seorang pahlawan nasional Indonesia. Soepomo dikenal sebagai arsitek Undang-undang Dasar 1945, bersama dengan Muhammad Yamin dan Soekarno"),
  Hero(id: 5, photo: "ki_hadjar_dewantara", name: "Ki Hadjar Dewantara", description: "Raden Mas Soewardi Soerjaningrat (EBI: Suwardi Suryaningrat, sejak 1922 menjadi Ki Hadjar Dewantara, EBI: Ki Hajar Dewantara, beberapa menuliskan bunyi bahasa Jawanya dengan Ki Hajar Dewantoro; lahir di Pakualaman, 2 Mei 1889 - meninggal di Yogyakarta, 26 April 1959 pada umur 69 tahun; selanjutnya disingkat sebagai \"Soewardi\" atau \"KHD\") adalah aktivis pergerakan kemerdekaan Indonesia, kolumnis, politisi, dan pelopor pendidikan bagi kaum pribumi Indonesia dari zaman penjajahan Belanda. Ia adalah pendiri Perguruan Taman Siswa, suatu lembaga pendidikan yang memberikan kesempatan bagi para pribumi untuk bisa memperoleh hak pendidikan seperti halnya para priyayi maupun orang-orang Belanda."),
  Hero(id: 6, photo: "mohammad_hatta", name: "Mohammad Hatta", description: "Dr.(HC) Drs. H. Mohammad Hatta (lahir dengan nama Mohammad Athar, dikenal sebagai Bung Hatta; lahir di Fort de Kock (sekarang Bukittinggi, Sumatera Barat), Hindia Belanda, 12 Agustus 1902 - meninggal di Jakarta, 14 Maret 1980 pada umur 77 tahun) adalah tokoh pejuang, negarawan, ekonom, dan juga Wakil Presiden Indonesia yang pertama. Ia bersama Soekarno memainkan peranan penting untuk memerdekakan bangsa Indonesia dari penjajahan Belanda sekaligus memproklamirkannya pada 17 Agustus 1945. Ia juga pernah menjabat sebagai Perdana Menteri dalam Kabinet Hatta I, Hatta II, dan RIS. Ia mundur dari jabatan wakil presiden pada tahun 1956, karena berselisih dengan Presiden Soekarno. Hatta juga dikenal sebagai Bapak Koperasi Indonesia."),
  Hero(id: 7, photo: "sudirman", name: "Soedirman", description: "Jenderal Besar Raden Soedirman (EYD: Sudirman; lahir 24 Januari 1916 - meninggal 29 Januari 1950 pada umur 34 tahun) adalah seorang perwira tinggi Indonesia pada masa Revolusi Nasional Indonesia. Menjadi panglima besar Tentara Nasional Indonesia pertama, ia secara luas terus dihormati di Indonesia. Terlahir dari pasangan rakyat biasa di Purbalingga, Hindia Belanda, Soedirman diadopsi oleh pamannya yang seorang priyayi. Setelah keluarganya pindah ke Cilacap pada tahun 1916, Soedirman tumbuh menjadi seorang siswa rajin; ia sangat aktif dalam kegiatan ekstrakurikuler, termasuk mengikuti program kepanduan yang dijalankan oleh organisasi Islam Muhammadiyah. Saat di sekolah menengah, Soedirman mulai menunjukkan kemampuannya dalam memimpin dan berorganisasi, dan dihormati oleh masyarakat karena ketaatannya pada Islam. Setelah berhenti kuliah keguruan, pada 1936 ia mulai bekerja sebagai seorang guru, dan kemudian menjadi kepala sekolah, di sekolah dasar Muhammadiyah; ia juga aktif dalam kegiatan Muhammadiyah lainnya dan menjadi pemimpin Kelompok Pemuda Muhammadiyah pada tahun 1937. Setelah Jepang menduduki Hindia Belanda pada 1942, Soedirman tetap mengajar. Pada tahun 1944, ia bergabung dengan tentara Pembela Tanah Air (PETA) yang disponsori Jepang, menjabat sebagai komandan batalion di Banyumas. Selama menjabat, Soedirman bersama rekannya sesama prajurit melakukan pemberontakan, namun kemudian diasingkan ke Bogor."),
  Hero(id: 8, photo: "sukarno", name: "Soekarno", description: "Dr.(H.C.) Ir. H. Soekarno (ER, EYD: Sukarno, nama lahir: Koesno Sosrodihardjo) (lahir di Surabaya, Jawa Timur, 6 Juni 1901 - meninggal di Jakarta, 21 Juni 1970 pada umur 69 tahun) adalah Presiden pertama Republik Indonesia yang menjabat pada periode 1945-1967. Ia memainkan peranan penting dalam memerdekakan bangsa Indonesia dari penjajahan Belanda. Ia adalah Proklamator Kemerdekaan Indonesia (bersama dengan Mohammad Hatta) yang terjadi pada tanggal 17 Agustus 1945. Soekarno adalah yang pertama kali mencetuskan konsep mengenai Pancasila sebagai dasar negara Indonesia dan ia sendiri yang menamainya.")
]
